### ISSUE TITLE
Roster: Section Editor – fix question mark CSS

### ISSUE THREAD

**Issue by ilyankou** [ram8647/gcb-clone-v111#12]
The text should appear on hover:

![screen shot 2017-06-20 at 16 41 25](https://user-images.githubusercontent.com/10443203/27354969-67593bc0-55d7-11e7-8cb2-9a144542ccfd.png)

**Comment by ilyankou** [comment]
**SOLUTION**

It appears that the Teacher module does not load Material Design CSS. In `modules/teacher/templates/teacher_dashboard.html`, somewhere around `lines 18-22`, add:
```html
<link rel="stylesheet" href="https://storage.googleapis.com/code.getmdl.io/1.0.0/material.teal-indigo.min.css">
```

It is being loaded by some other modules (`dashboard` and `oeditor`), so in theory it will simply be taken from cache, not loaded from the web.

**Comment by ram8647** [comment]
Fixed.
